alias: _new climate schema
description: >-
  You can copy this code in a newly created automation in the YAML editor.

  Remove anything and paste this code. After that, you could return to the
  visual editor for further changes.

  In the trigger you should change the entity_id and in the first variables
  block you should change name to suit the zone you want to regulate. In this
  example it is ‘Woonkamer’. 
 
  The automation is called every 20 minutes, or when one of the set points is
  changed or when the schedule is overruled by manual setting the temperature. 
trigger:
  - platform: time_pattern
    minutes: /20
  - platform: state
    entity_id:
      - input_number.woonkamer_man_temp
  - platform: time
    at: "11:32:00"
  - platform: time
    at: "14:32:00"
  - platform: time
    at: "17:02:00"
condition: []
action:
  - variables:
      name: woonkamer
      real_term: climate.{{name}}
      fake_term: climate.{{name}}_fake_thermostat
      delta_var: input_number.delta_{{name}}
      temp_override: input_number.{{name}}_man_temp
      current_temp: "{{ state_attr(real_term, 'current_temperature') | float(0) }}"
      target_temp: "{{ state_attr(fake_term, 'temperature') | float(0) }}"
  - alias: "Manual override, setpoint or EH schedule "
    if:
      - alias: Test for manual override is lower than 15 (no override)
        condition: template
        value_template: "{{ (states(temp_override) | float ) < 15}}"
    then:
      - alias: Select setpoint actions or standard actions
        choose:
          - conditions:
              - alias: Setpoint period 1, 20° weekend
                condition: or
                conditions:
                  - condition: time
                    after: "11:30:00"
                    before: "17:00:00"
                    weekday:
                      - sat
                      - sun
            sequence:
              - service: climate.set_temperature
                data:
                  temperature: 20
                target:
                  entity_id:
                    - "{{fake_term}}"
          - conditions:
              - alias: Setpoint period 1, 20° week
                condition: or
                conditions:
                  - condition: time
                    after: "14:30:00"
                    before: "17:00:00"
                    weekday:
                      - mon
                      - tue
                      - wed
                      - thu
                      - fri
            sequence:
              - service: climate.set_temperature
                data:
                  temperature: 20
                target:
                  entity_id:
                    - "{{fake_term}}"
          - conditions:
              - alias: Setpoint period 2 20,5° Weekend
                condition: or
                conditions:
                  - condition: time
                    after: "17:00:00"
                    before: "23:30:00"
                    weekday:
                      - sat
                      - fri
            sequence:
              - service: climate.set_temperature
                data:
                  temperature: 20,5
                target:
                  entity_id:
                    - "{{fake_term}}"
          - conditions:
              - alias: Setpoint period 2 20,5° week
                condition: or
                conditions:
                  - condition: time
                    after: "17:00:00"
                    before: "22:30:00"
                    weekday:
                      - mon
                      - tue
                      - wed
                      - thu
                      - sun
            sequence:
              - service: climate.set_temperature
                data:
                  temperature: 20,5
                target:
                  entity_id:
                    - "{{fake_term}}"
        default:
          - service: climate.set_temperature
            data:
              temperature: 19
            target:
              entity_id:
                - "{{fake_term}}"
    else:
      - variables:
          setpoint_temp: "{{ states(temp_override) }}"
      - service: climate.set_temperature
        data:
          temperature: "{{setpoint_temp}}"
        target:
          entity_id:
            - "{{fake_term}}"
  - alias: Set Delta temperature
    choose:
      - conditions:
          - condition: template
            value_template: "{{current_temp < (target_temp - 1)}}"
        sequence:
          - service: input_number.set_value
            data:
              value: 0.5
            target:
              entity_id: "{{delta_var}}"
      - conditions:
          - condition: template
            value_template: "{{current_temp < (target_temp - 0.5)}}"
        sequence:
          - service: input_number.set_value
            data:
              value: 0.3
            target:
              entity_id: "{{delta_var}}"
    default:
      - service: input_number.set_value
        data:
          value: 0.1
        target:
          entity_id: "{{delta_var}}"
  - alias: Reset manual override after 23:50
    if:
      - condition: time
        after: "23:49:00"
        before: "23:59:00"
    then:
      - service: input_number.set_value
        target:
          entity_id: "{{temp_override}}"
        data:
          value: 0
mode: single
